# Modified from https://github.com/Pebaz/nimporter/blob/f472fd23988702ab23450e85a92c8ee07b9977f2/examples/github_actions_template.yml

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -O https://nim-lang.org/choosenim/init.sh
          sh init.sh -y
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          export PATH=/github/home/.nimble/bin:$PATH
          cd $GITHUB_WORKSPACE
          choosenim 1.4.0
          nim -v
          cd librtd
          nimble install -Y
          cd ../librtd-py/librtdpy
          nimble install -Y
          cd ../
          for PYBIN in /opt/python/*/bin/; do 
            if ! test $PYBIN -ef /opt/python/cp35-cp35m/bin/; then
              "${PYBIN}/pip" install setuptools wheel twine nimporter>=1.0.2
              "${PYBIN}/pip" wheel . --no-deps -w wheelhouse/
            fi
          done
          ls dist
