# Modified from https://github.com/Pebaz/nimporter/blob/f472fd23988702ab23450e85a92c8ee07b9977f2/examples/github_actions_template.yml

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - run: ls /github
      - name: Install Nim
        run: |
          cd ~
          curl -O https://nim-lang.org/choosenim/init.sh
          sh init.sh -y
          export PATH=/root/.nimble/bin:$PATH
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine nimporter>=1.0.2
          cd librtd
          nimble install -Y
          cd ../librtd-py
          cd librtdpy
          nimble install -Y
          cd ../
          python setup.py bdist_wheel
          WHEEL=dist/$(python3 -c 'import pathlib;print([*pathlib.Path("dist").glob("benjamin-lee*")][0].name.replace("linux", "manylinux1"))')
          mv dist/$(python -c "import pathlib;print([*pathlib.Path('dist').glob('benjamin-lee*')][0].name)") $WHEEL
          ls dist
