# Modified from https://github.com/Pebaz/nimporter/blob/f472fd23988702ab23450e85a92c8ee07b9977f2/examples/github_actions_template.yml
# Linux build steps modified from https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh

name: Release

on:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -O https://nim-lang.org/choosenim/init.sh
          sh init.sh -y
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          export PATH=/github/home/.nimble/bin:$PATH
          cd $GITHUB_WORKSPACE
          choosenim 1.4.0
          nim -v
          cd librtd
          nimble install -Y
          cd ../librtd-py/librtdpy
          nimble install -Y
          cd ../
          for PYBIN in /opt/python/*/bin/; do 
            if ! test $PYBIN -ef /opt/python/cp35-cp35m/bin/; then
              "${PYBIN}/pip" install setuptools wheel twine nimporter>=1.0.2
              "${PYBIN}/pip" wheel . --no-deps -w wheelhouse/
            fi
          done
          mkdir repaired
          for whl in wheelhouse/*.whl; do
              auditwheel repair "$whl" -w repaired
          done
          /opt/python/cp39-cp39/bin/twine upload repaired/*

  build-win32:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: jiro4989/setup-nim-action@v1.3.14
        with:
          nim-version: "1.4.0"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine nimporter>=1.0.2
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd librtd
          nimble install -Y
          cd ../librtd-py
          cd librtdpy
          nimble install -Y
          cd ../
          python setup.py bdist_wheel
          twine upload dist/*

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: jiro4989/setup-nim-action@v1.3.14
        with:
          nim-version: "1.4.0"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools wheel twine nimporter>=1.0.2
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          cd librtd
          nimble install -Y
          cd ../librtd-py
          cd librtdpy
          nimble install -Y
          cd ../
          python setup.py bdist_wheel
          twine upload dist/*
